var data = [
  { acidity: 6.0, sweetness: 6.7, taste: 6.0 },
  { acidity: 6.3, sweetness: 5.3, taste: 4.7 },
  { acidity: 4.0, sweetness: 4.0, taste: 3.7 },
  { acidity: 4.3, sweetness: 4.7, taste: 4.7 },
  { acidity: 5.0, sweetness: 4.3, taste: 3.7 },
  { acidity: 4.7, sweetness: 6.0, taste: 6.3 },
  { acidity: 5.7, sweetness: 3.7, taste: 3.0 },
  { acidity: 4.0, sweetness: 4.3, taste: 3.7 },
  { acidity: 4.7, sweetness: 4.7, taste: 4.0 },
  { acidity: 4.3, sweetness: 5.3, taste: 5.7 },
  { acidity: 5.3, sweetness: 6.0, taste: 5.7 },
  { acidity: 6.0, sweetness: 5.7, taste: 5.0 },
  { acidity: 4.3, sweetness: 5.0, taste: 5.0 },
  { acidity: 4.7, sweetness: 6.3, taste: 5.3 },
  { acidity: 3.0, sweetness: 5.7, taste: 4.7 },
  { acidity: 5.0, sweetness: 5.3, taste: 5.0 },
  { acidity: 4.3, sweetness: 5.7, taste: 4.0 },
  { acidity: 4.3, sweetness: 5.0, taste: 5.3 },
  { acidity: 5.0, sweetness: 7.0, taste: 6.7 },
  { acidity: 5.0, sweetness: 5.0, taste: 5.0 },
  { acidity: 5.0, sweetness: 5.7, taste: 5.0 },
  { acidity: 4.0, sweetness: 5.0, taste: 4.7 },
  { acidity: 4.0, sweetness: 4.3, taste: 4.0 },
  { acidity: 3.7, sweetness: 5.3, taste: 4.7 },
  { acidity: 4.0, sweetness: 5.7, taste: 4.0 },
  { acidity: 2.7, sweetness: 5.3, taste: 4.3 },
  { acidity: 3.7, sweetness: 4.3, taste: 3.7 },
  { acidity: 3.0, sweetness: 4.0, taste: 4.3 },
  { acidity: 3.7, sweetness: 4.3, taste: 4.7 },
  { acidity: 3.7, sweetness: 4.3, taste: 4.3 },
];

const data2 = [
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 1,
    closestGroupNumber: 1,
    newGroupNumber: 1,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次001000_工作區域 1.jpg",
    modelpath: "./assets/01.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 2,
    closestGroupNumber: 1,
    newGroupNumber: 2,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次002000_工作區域 1.jpg",
    modelpath: "./assets/02.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 2,
    closestGroupNumber: 2,
    newGroupNumber: 2,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次003000_工作區域 1.jpg",
    modelpath: "./assets/02.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 3,
    newGroupNumber: 3,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次004000_工作區域 1.jpg",
    modelpath: "./assets/03.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 1,
    newGroupNumber: 4,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次005000_工作區域 1.jpg",
    modelpath: "./assets/04.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 5,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次006000_工作區域 1.jpg",
    modelpath: "./assets/05.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 1,
    newGroupNumber: 6,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次007000_工作區域 1.jpg",
    modelpath: "./assets/06.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 7,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次008000_工作區域 1.jpg",
    modelpath: "./assets/07.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 1,
    newGroupNumber: 8,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次009000_工作區域 1.jpg",
    modelpath: "./assets/08.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 1,
    newGroupNumber: 9,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次010000_工作區域 1.jpg",
    modelpath: "./assets/09.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 9,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次011000_工作區域 1.jpg",
    modelpath: "./assets/09.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 1,
    newGroupNumber: 10,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次012000_工作區域 1.jpg",
    modelpath: "./assets/10.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 10,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次013000_工作區域 1.jpg",
    modelpath: "./assets/10.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 11,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次014000_工作區域 1.jpg",
    modelpath: "./assets/11.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 1,
    newGroupNumber: 12,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次015000_工作區域 1.jpg",
    modelpath: "./assets/12.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 13,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次016000_工作區域 1.jpg",
    modelpath: "./assets/13.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 1,
    newGroupNumber: 14,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次017000_工作區域 1.jpg",
    modelpath: "./assets/14.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 15,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次018000_工作區域 1.jpg",
    modelpath: "./assets/15.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 1,
    newGroupNumber: 16,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次019000_工作區域 1.jpg",
    modelpath: "./assets/16.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 2,
    closestGroupNumber: 2,
    newGroupNumber: 17,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次020000_工作區域 1.jpg",
    modelpath: "./assets/17.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 3,
    newGroupNumber: 18,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次021000_工作區域 1.jpg",
    modelpath: "./assets/18.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 2,
    newGroupNumber: 19,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次022000_工作區域 1.jpg",
    modelpath: "./assets/19.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 20,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次023000_工作區域 1.jpg",
    modelpath: "./assets/20.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 2,
    newGroupNumber: 21,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次024000_工作區域 1.jpg",
    modelpath: "./assets/21.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 22,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次025000_工作區域 1.jpg",
    modelpath: "./assets/22.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 2,
    newGroupNumber: 23,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次026000_工作區域 1.jpg",
    modelpath: "./assets/23.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 2,
    newGroupNumber: 24,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次027000_工作區域 1.jpg",
    modelpath: "./assets/24.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 24,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次028000_工作區域 1.jpg",
    modelpath: "./assets/24.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 2,
    newGroupNumber: 25,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次029000_工作區域 1.jpg",
    modelpath: "./assets/25.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 25,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次030000_工作區域 1.jpg",
    modelpath: "./assets/25.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 26,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次031000_工作區域 1.jpg",
    modelpath: "./assets/26.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 2,
    newGroupNumber: 27,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次032000_工作區域 1.jpg",
    modelpath: "./assets/27.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 28,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次033000_工作區域 1.jpg",
    modelpath: "./assets/28.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 2,
    newGroupNumber: 29,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次034000_工作區域 1.jpg",
    modelpath: "./assets/29.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 30,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次035000_工作區域 1.jpg",
    modelpath: "./assets/30.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 2,
    newGroupNumber: 31,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次036000_工作區域 1.jpg",
    modelpath: "./assets/31.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 3,
    newGroupNumber: 32,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次037000_工作區域 1.jpg",
    modelpath: "./assets/32.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 3,
    newGroupNumber: 33,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次038000_工作區域 1.jpg",
    modelpath: "./assets/33.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 33,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次039000_工作區域 1.jpg",
    modelpath: "./assets/33.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 3,
    newGroupNumber: 34,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次040000_工作區域 1.jpg",
    modelpath: "./assets/34.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 34,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次041000_工作區域 1.jpg",
    modelpath: "./assets/34.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 3,
    newGroupNumber: 35,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次042000_工作區域 1.jpg",
    modelpath: "./assets/35.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 36,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次043000_工作區域 1.jpg",
    modelpath: "./assets/36.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 3,
    newGroupNumber: 37,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次044000_工作區域 1.jpg",
    modelpath: "./assets/37.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 38,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次045000_工作區域 1.jpg",
    modelpath: "./assets/38.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 3,
    newGroupNumber: 39,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次046000_工作區域 1.jpg",
    modelpath: "./assets/39.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 39,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次047000_工作區域 1.jpg",
    modelpath: "./assets/39.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 3,
    newGroupNumber: 40,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次048000_工作區域 1.jpg",
    modelpath: "./assets/40.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 40,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次049000_工作區域 1.jpg",
    modelpath: "./assets/40.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 3,
    newGroupNumber: 41,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次050000_工作區域 1.jpg",
    modelpath: "./assets/41.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 41,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次051000_工作區域 1.jpg",
    modelpath: "./assets/41.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 42,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次052000_工作區域 1.jpg",
    modelpath: "./assets/42.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 4,
    newGroupNumber: 43,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次053000_工作區域 1.jpg",
    modelpath: "./assets/43.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 43,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次054000_工作區域 1.jpg",
    modelpath: "./assets/43.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 4,
    newGroupNumber: 44,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次055000_工作區域 1.jpg",
    modelpath: "./assets/44.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 45,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次056000_工作區域 1.jpg",
    modelpath: "./assets/45.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 4,
    newGroupNumber: 46,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次057000_工作區域 1.jpg",
    modelpath: "./assets/46.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 47,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次058000_工作區域 1.jpg",
    modelpath: "./assets/47.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 4,
    newGroupNumber: 48,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次059000_工作區域 1.jpg",
    modelpath: "./assets/48.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 48,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次060000_工作區域 1.jpg",
    modelpath: "./assets/48.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 4,
    newGroupNumber: 49,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次061000_工作區域 1.jpg",
    modelpath: "./assets/49.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 49,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次062000_工作區域 1.jpg",
    modelpath: "./assets/49.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 4,
    newGroupNumber: 50,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次063000_工作區域 1.jpg",
    modelpath: "./assets/50.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 50,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次064000_工作區域 1.jpg",
    modelpath: "./assets/50.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 51,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次065000_工作區域 1.jpg",
    modelpath: "./assets/51.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 5,
    newGroupNumber: 52,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次066000_工作區域 1.jpg",
    modelpath: "./assets/52.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 53,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次067000_工作區域 1.jpg",
    modelpath: "./assets/53.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 5,
    newGroupNumber: 54,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次068000_工作區域 1.jpg",
    modelpath: "./assets/54.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 55,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次069000_工作區域 1.jpg",
    modelpath: "./assets/55.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 5,
    newGroupNumber: 56,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次070000_工作區域 1.jpg",
    modelpath: "./assets/56.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 56,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次071000_工作區域 1.jpg",
    modelpath: "./assets/56.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 5,
    newGroupNumber: 57,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次072000_工作區域 1.jpg",
    modelpath: "./assets/57.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 57,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次073000_工作區域 1.jpg",
    modelpath: "./assets/57.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 5,
    newGroupNumber: 58,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次074000_工作區域 1.jpg",
    modelpath: "./assets/58.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 58,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次075000_工作區域 1.jpg",
    modelpath: "./assets/58.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 59,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次076000_工作區域 1.jpg",
    modelpath: "./assets/59.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 6,
    newGroupNumber: 60,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次077000_工作區域 1.jpg",
    modelpath: "./assets/60.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 60,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次078000_工作區域 1.jpg",
    modelpath: "./assets/60.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 61,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次079000_工作區域 1.jpg",
    modelpath: "./assets/61.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 6,
    newGroupNumber: 62,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次080000_工作區域 1.jpg",
    modelpath: "./assets/62.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 63,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次081000_工作區域 1.jpg",
    modelpath: "./assets/63.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 6,
    newGroupNumber: 64,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次082000_工作區域 1.jpg",
    modelpath: "./assets/64.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 65,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次083000_工作區域 1.jpg",
    modelpath: "./assets/65.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 6,
    newGroupNumber: 66,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次084000_工作區域 1.jpg",
    modelpath: "./assets/66.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 67,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次085000_工作區域 1.jpg",
    modelpath: "./assets/67.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 68,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次086000_工作區域 1.jpg",
    modelpath: "./assets/68.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 7,
    newGroupNumber: 69,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次087000_工作區域 1.jpg",
    modelpath: "./assets/69.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 70,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次088000_工作區域 1.jpg",
    modelpath: "./assets/70.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 7,
    newGroupNumber: 71,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次089000_工作區域 1.jpg",
    modelpath: "./assets/71.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 72,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次090000_工作區域 1.jpg",
    modelpath: "./assets/72.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 7,
    newGroupNumber: 73,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次091000_工作區域 1.jpg",
    modelpath: "./assets/73.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 74,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次092000_工作區域 1.jpg",
    modelpath: "./assets/74.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 8,
    newGroupNumber: 75,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次093000_工作區域 1.jpg",
    modelpath: "./assets/75.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 75,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次094000_工作區域 1.jpg",
    modelpath: "./assets/75.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 8,
    newGroupNumber: 76,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次095000_工作區域 1.jpg",
    modelpath: "./assets/76.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 76,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次096000_工作區域 1.jpg",
    modelpath: "./assets/76.glb",
  },
  {
    bestNegativeGroupNumber: 9,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 77,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次097000_工作區域 1.jpg",
    modelpath: "./assets/77.glb",
  },
  {
    bestNegativeGroupNumber: 9,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 9,
    newGroupNumber: 78,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次098000_工作區域 1.jpg",
    modelpath: "./assets/78.glb",
  },
  {
    bestNegativeGroupNumber: 9,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 78,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次099000_工作區域 1.jpg",
    modelpath: "./assets/78.glb",
  },
  {
    bestNegativeGroupNumber: 10,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 79,
    path: "image/dripperinfro/論文-濾杯結構說明圖-批次100000_工作區域 1.jpg",
    modelpath: "./assets/79.glb",
  },
];
