var data = [
  { acidity: 6.0, sweetness: 6.7, taste: 6.0 },
  { acidity: 6.3, sweetness: 5.3, taste: 4.7 },
  { acidity: 4.0, sweetness: 4.0, taste: 3.7 },
  { acidity: 4.3, sweetness: 4.7, taste: 4.7 },
  { acidity: 5.0, sweetness: 4.3, taste: 3.7 },
  { acidity: 4.7, sweetness: 6.0, taste: 6.3 },
  { acidity: 5.7, sweetness: 3.7, taste: 3.0 },
  { acidity: 4.0, sweetness: 4.3, taste: 3.7 },
  { acidity: 4.7, sweetness: 4.7, taste: 4.0 },
  { acidity: 4.3, sweetness: 5.3, taste: 5.7 },
  { acidity: 5.3, sweetness: 6.0, taste: 5.7 },
  { acidity: 6.0, sweetness: 5.7, taste: 5.0 },
  { acidity: 4.3, sweetness: 5.0, taste: 5.0 },
  { acidity: 4.7, sweetness: 6.3, taste: 5.3 },
  { acidity: 3.0, sweetness: 5.7, taste: 4.7 },
  { acidity: 5.0, sweetness: 5.3, taste: 5.0 },
  { acidity: 4.3, sweetness: 5.7, taste: 4.0 },
  { acidity: 4.3, sweetness: 5.0, taste: 5.3 },
  { acidity: 5.0, sweetness: 7.0, taste: 6.7 },
  { acidity: 5.0, sweetness: 5.0, taste: 5.0 },
  { acidity: 5.0, sweetness: 5.7, taste: 5.0 },
  { acidity: 4.0, sweetness: 5.0, taste: 4.7 },
  { acidity: 4.0, sweetness: 4.3, taste: 4.0 },
  { acidity: 3.7, sweetness: 5.3, taste: 4.7 },
  { acidity: 4.0, sweetness: 5.7, taste: 4.0 },
  { acidity: 2.7, sweetness: 5.3, taste: 4.3 },
  { acidity: 3.7, sweetness: 4.3, taste: 3.7 },
  { acidity: 3.0, sweetness: 4.0, taste: 4.3 },
  { acidity: 3.7, sweetness: 4.3, taste: 4.7 },
  { acidity: 3.7, sweetness: 4.3, taste: 4.3 },
];

const data2 = [
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 1,
    closestGroupNumber: 1,
    newGroupNumber: 1,
    path: "image/dripperinfro/資料組 1_濾杯結構.jpg",
    modelpath: "./assets/01.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 2,
    closestGroupNumber: 1,
    newGroupNumber: 2,
    path: "image/dripperinfro/資料組 2_濾杯結構.jpg",
    modelpath: "./assets/02.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 2,
    closestGroupNumber: 2,
    newGroupNumber: 2,
    path: "image/dripperinfro/資料組 3_濾杯結構.jpg",
    modelpath: "./assets/02.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 3,
    newGroupNumber: 3,
    path: "image/dripperinfro/資料組 4_濾杯結構.jpg",
    modelpath: "./assets/03.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 1,
    newGroupNumber: 4,
    path: "image/dripperinfro/資料組 5_濾杯結構.jpg",
    modelpath: "./assets/04.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 5,
    path: "image/dripperinfro/資料組 6_濾杯結構.jpg",
    modelpath: "./assets/05.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 1,
    newGroupNumber: 6,
    path: "image/dripperinfro/資料組 7_濾杯結構.jpg",
    modelpath: "./assets/06.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 7,
    path: "image/dripperinfro/資料組 8_濾杯結構.jpg",
    modelpath: "./assets/07.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 1,
    newGroupNumber: 8,
    path: "image/dripperinfro/資料組 9_濾杯結構.jpg",
    modelpath: "./assets/08.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 1,
    newGroupNumber: 9,
    path: "image/dripperinfro/資料組 10_濾杯結構.jpg",
    modelpath: "./assets/09.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 9,
    path: "image/dripperinfro/資料組 11_濾杯結構.jpg",
    modelpath: "./assets/09.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 1,
    newGroupNumber: 10,
    path: "image/dripperinfro/資料組 12_濾杯結構.jpg",
    modelpath: "./assets/10.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 10,
    path: "image/dripperinfro/資料組 13_濾杯結構.jpg",
    modelpath: "./assets/10.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 11,
    path: "image/dripperinfro/資料組 14_濾杯結構.jpg",
    modelpath: "./assets/11.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 1,
    newGroupNumber: 12,
    path: "image/dripperinfro/資料組 15_濾杯結構.jpg",
    modelpath: "./assets/12.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 13,
    path: "image/dripperinfro/資料組 16_濾杯結構.jpg",
    modelpath: "./assets/13.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 1,
    newGroupNumber: 14,
    path: "image/dripperinfro/資料組 17_濾杯結構.jpg",
    modelpath: "./assets/14.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 15,
    path: "image/dripperinfro/資料組 18_濾杯結構.jpg",
    modelpath: "./assets/15.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 1,
    newGroupNumber: 16,
    path: "image/dripperinfro/資料組 19_濾杯結構.jpg",
    modelpath: "./assets/16.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 2,
    closestGroupNumber: 2,
    newGroupNumber: 17,
    path: "image/dripperinfro/資料組 20_濾杯結構.jpg",
    modelpath: "./assets/17.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 3,
    newGroupNumber: 18,
    path: "image/dripperinfro/資料組 21_濾杯結構.jpg",
    modelpath: "./assets/18.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 2,
    newGroupNumber: 19,
    path: "image/dripperinfro/資料組 22_濾杯結構.jpg",
    modelpath: "./assets/19.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 20,
    path: "image/dripperinfro/資料組 23_濾杯結構.jpg",
    modelpath: "./assets/20.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 2,
    newGroupNumber: 21,
    path: "image/dripperinfro/資料組 24_濾杯結構.jpg",
    modelpath: "./assets/21.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 22,
    path: "image/dripperinfro/資料組 25_濾杯結構.jpg",
    modelpath: "./assets/22.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 2,
    newGroupNumber: 23,
    path: "image/dripperinfro/資料組 26_濾杯結構.jpg",
    modelpath: "./assets/23.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 2,
    newGroupNumber: 24,
    path: "image/dripperinfro/資料組 27_濾杯結構.jpg",
    modelpath: "./assets/24.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 24,
    path: "image/dripperinfro/資料組 28_濾杯結構.jpg",
    modelpath: "./assets/24.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 2,
    newGroupNumber: 25,
    path: "image/dripperinfro/資料組 29_濾杯結構.jpg",
    modelpath: "./assets/25.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 25,
    path: "image/dripperinfro/資料組 30_濾杯結構.jpg",
    modelpath: "./assets/25.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 26,
    path: "image/dripperinfro/資料組 31_濾杯結構.jpg",
    modelpath: "./assets/26.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 2,
    newGroupNumber: 27,
    path: "image/dripperinfro/資料組 32_濾杯結構.jpg",
    modelpath: "./assets/27.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 28,
    path: "image/dripperinfro/資料組 33_濾杯結構.jpg",
    modelpath: "./assets/28.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 2,
    newGroupNumber: 29,
    path: "image/dripperinfro/資料組 34_濾杯結構.jpg",
    modelpath: "./assets/29.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 30,
    path: "image/dripperinfro/資料組 35_濾杯結構.jpg",
    modelpath: "./assets/30.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 2,
    newGroupNumber: 31,
    path: "image/dripperinfro/資料組 36_濾杯結構.jpg",
    modelpath: "./assets/31.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 3,
    newGroupNumber: 32,
    path: "image/dripperinfro/資料組 37_濾杯結構.jpg",
    modelpath: "./assets/32.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 3,
    newGroupNumber: 33,
    path: "image/dripperinfro/資料組 38_濾杯結構.jpg",
    modelpath: "./assets/33.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 33,
    path: "image/dripperinfro/資料組 39_濾杯結構.jpg",
    modelpath: "./assets/33.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 3,
    newGroupNumber: 34,
    path: "image/dripperinfro/資料組 40_濾杯結構.jpg",
    modelpath: "./assets/34.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 34,
    path: "image/dripperinfro/資料組 41_濾杯結構.jpg",
    modelpath: "./assets/34.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 3,
    newGroupNumber: 35,
    path: "image/dripperinfro/資料組 42_濾杯結構.jpg",
    modelpath: "./assets/35.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 36,
    path: "image/dripperinfro/資料組 43_濾杯結構.jpg",
    modelpath: "./assets/36.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 3,
    newGroupNumber: 37,
    path: "image/dripperinfro/資料組 44_濾杯結構.jpg",
    modelpath: "./assets/37.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 38,
    path: "image/dripperinfro/資料組 45_濾杯結構.jpg",
    modelpath: "./assets/38.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 3,
    newGroupNumber: 39,
    path: "image/dripperinfro/資料組 46_濾杯結構.jpg",
    modelpath: "./assets/39.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 39,
    path: "image/dripperinfro/資料組 47_濾杯結構.jpg",
    modelpath: "./assets/39.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 3,
    newGroupNumber: 40,
    path: "image/dripperinfro/資料組 48_濾杯結構.jpg",
    modelpath: "./assets/40.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 40,
    path: "image/dripperinfro/資料組 49_濾杯結構.jpg",
    modelpath: "./assets/40.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 3,
    newGroupNumber: 41,
    path: "image/dripperinfro/資料組 50_濾杯結構.jpg",
    modelpath: "./assets/41.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 41,
    path: "image/dripperinfro/資料組 51_濾杯結構.jpg",
    modelpath: "./assets/41.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 42,
    path: "image/dripperinfro/資料組 52_濾杯結構.jpg",
    modelpath: "./assets/42.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 4,
    newGroupNumber: 43,
    path: "image/dripperinfro/資料組 53_濾杯結構.jpg",
    modelpath: "./assets/43.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 43,
    path: "image/dripperinfro/資料組 54_濾杯結構.jpg",
    modelpath: "./assets/43.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 4,
    newGroupNumber: 44,
    path: "image/dripperinfro/資料組 55_濾杯結構.jpg",
    modelpath: "./assets/44.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 45,
    path: "image/dripperinfro/資料組 56_濾杯結構.jpg",
    modelpath: "./assets/45.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 4,
    newGroupNumber: 46,
    path: "image/dripperinfro/資料組 57_濾杯結構.jpg",
    modelpath: "./assets/46.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 47,
    path: "image/dripperinfro/資料組 58_濾杯結構.jpg",
    modelpath: "./assets/47.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 4,
    newGroupNumber: 48,
    path: "image/dripperinfro/資料組 59_濾杯結構.jpg",
    modelpath: "./assets/48.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 48,
    path: "image/dripperinfro/資料組 60_濾杯結構.jpg",
    modelpath: "./assets/48.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 4,
    newGroupNumber: 49,
    path: "image/dripperinfro/資料組 61_濾杯結構.jpg",
    modelpath: "./assets/49.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 49,
    path: "image/dripperinfro/資料組 62_濾杯結構.jpg",
    modelpath: "./assets/49.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 4,
    newGroupNumber: 50,
    path: "image/dripperinfro/資料組 63_濾杯結構.jpg",
    modelpath: "./assets/50.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 50,
    path: "image/dripperinfro/資料組 64_濾杯結構.jpg",
    modelpath: "./assets/50.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 51,
    path: "image/dripperinfro/資料組 65_濾杯結構.jpg",
    modelpath: "./assets/51.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 5,
    newGroupNumber: 52,
    path: "image/dripperinfro/資料組 66_濾杯結構.jpg",
    modelpath: "./assets/52.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 53,
    path: "image/dripperinfro/資料組 67_濾杯結構.jpg",
    modelpath: "./assets/53.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 5,
    newGroupNumber: 54,
    path: "image/dripperinfro/資料組 68_濾杯結構.jpg",
    modelpath: "./assets/54.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 55,
    path: "image/dripperinfro/資料組 69_濾杯結構.jpg",
    modelpath: "./assets/55.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 5,
    newGroupNumber: 56,
    path: "image/dripperinfro/資料組 70_濾杯結構.jpg",
    modelpath: "./assets/56.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 56,
    path: "image/dripperinfro/資料組 71_濾杯結構.jpg",
    modelpath: "./assets/56.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 5,
    newGroupNumber: 57,
    path: "image/dripperinfro/資料組 72_濾杯結構.jpg",
    modelpath: "./assets/57.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 57,
    path: "image/dripperinfro/資料組 73_濾杯結構.jpg",
    modelpath: "./assets/57.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 5,
    newGroupNumber: 58,
    path: "image/dripperinfro/資料組 74_濾杯結構.jpg",
    modelpath: "./assets/58.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 58,
    path: "image/dripperinfro/資料組 75_濾杯結構.jpg",
    modelpath: "./assets/58.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 59,
    path: "image/dripperinfro/資料組 76_濾杯結構.jpg",
    modelpath: "./assets/59.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 6,
    newGroupNumber: 60,
    path: "image/dripperinfro/資料組 77_濾杯結構.jpg",
    modelpath: "./assets/60.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 60,
    path: "image/dripperinfro/資料組 78_濾杯結構.jpg",
    modelpath: "./assets/60.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 61,
    path: "image/dripperinfro/資料組 79_濾杯結構.jpg",
    modelpath: "./assets/61.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 6,
    newGroupNumber: 62,
    path: "image/dripperinfro/資料組 80_濾杯結構.jpg",
    modelpath: "./assets/62.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 63,
    path: "image/dripperinfro/資料組 81_濾杯結構.jpg",
    modelpath: "./assets/63.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 6,
    newGroupNumber: 64,
    path: "image/dripperinfro/資料組 82_濾杯結構.jpg",
    modelpath: "./assets/64.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 65,
    path: "image/dripperinfro/資料組 83_濾杯結構.jpg",
    modelpath: "./assets/65.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 6,
    newGroupNumber: 66,
    path: "image/dripperinfro/資料組 84_濾杯結構.jpg",
    modelpath: "./assets/66.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 67,
    path: "image/dripperinfro/資料組 85_濾杯結構.jpg",
    modelpath: "./assets/67.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 68,
    path: "image/dripperinfro/資料組 86_濾杯結構.jpg",
    modelpath: "./assets/68.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 7,
    newGroupNumber: 69,
    path: "image/dripperinfro/資料組 87_濾杯結構.jpg",
    modelpath: "./assets/69.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 70,
    path: "image/dripperinfro/資料組 88_濾杯結構.jpg",
    modelpath: "./assets/70.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 7,
    newGroupNumber: 71,
    path: "image/dripperinfro/資料組 89_濾杯結構.jpg",
    modelpath: "./assets/71.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 72,
    path: "image/dripperinfro/資料組 90_濾杯結構.jpg",
    modelpath: "./assets/72.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 7,
    newGroupNumber: 73,
    path: "image/dripperinfro/資料組 91_濾杯結構.jpg",
    modelpath: "./assets/73.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 74,
    path: "image/dripperinfro/資料組 92_濾杯結構.jpg",
    modelpath: "./assets/74.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 8,
    newGroupNumber: 75,
    path: "image/dripperinfro/資料組 93_濾杯結構.jpg",
    modelpath: "./assets/75.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 75,
    path: "image/dripperinfro/資料組 94_濾杯結構.jpg",
    modelpath: "./assets/75.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 8,
    newGroupNumber: 76,
    path: "image/dripperinfro/資料組 95_濾杯結構.jpg",
    modelpath: "./assets/76.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 76,
    path: "image/dripperinfro/資料組 96_濾杯結構.jpg",
    modelpath: "./assets/76.glb",
  },
  {
    bestNegativeGroupNumber: 9,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 77,
    path: "image/dripperinfro/資料組 97_濾杯結構.jpg",
    modelpath: "./assets/77.glb",
  },
  {
    bestNegativeGroupNumber: 9,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 9,
    newGroupNumber: 78,
    path: "image/dripperinfro/資料組 98_濾杯結構.jpg",
    modelpath: "./assets/78.glb",
  },
  {
    bestNegativeGroupNumber: 9,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 78,
    path: "image/dripperinfro/資料組 99_濾杯結構.jpg",
    modelpath: "./assets/78.glb",
  },
  {
    bestNegativeGroupNumber: 10,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 79,
    path: "image/dripperinfro/資料組 100_濾杯結構.jpg",
    modelpath: "./assets/79.glb",
  },
];
