const data = [
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 1,
    closestGroupNumber: 1,
    newGroupNumber: 1,
    path: "image/test/數字-01.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 2,
    closestGroupNumber: 1,
    newGroupNumber: 2,
    path: "image/test/數字-02.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 2,
    closestGroupNumber: 2,
    newGroupNumber: 2,
    path: "image/test/數字-02.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 3,
    newGroupNumber: 3,
    path: "image/test/數字-03.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 1,
    newGroupNumber: 4,
    path: "image/test/數字-04.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 5,
    path: "image/test/數字-05.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 1,
    newGroupNumber: 6,
    path: "image/test/數字-06.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 7,
    path: "image/test/數字-07.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 1,
    newGroupNumber: 8,
    path: "image/test/數字-08.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 1,
    newGroupNumber: 9,
    path: "image/test/數字-09.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 9,
    path: "image/test/數字-09.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 1,
    newGroupNumber: 10,
    path: "image/test/數字-10.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 10,
    path: "image/test/數字-10.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 11,
    path: "image/test/數字-11.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 1,
    newGroupNumber: 12,
    path: "image/test/數字-12.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 13,
    path: "image/test/數字-13.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 1,
    newGroupNumber: 14,
    path: "image/test/數字-14.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 15,
    path: "image/test/數字-15.jpg",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 1,
    newGroupNumber: 16,
    path: "image/test/數字-16.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 2,
    closestGroupNumber: 2,
    newGroupNumber: 17,
    path: "image/test/數字-17.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 3,
    newGroupNumber: 18,
    path: "image/test/數字-18.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 2,
    newGroupNumber: 19,
    path: "image/test/數字-19.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 20,
    path: "image/test/數字-20.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 2,
    newGroupNumber: 21,
    path: "image/test/數字-21.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 22,
    path: "image/test/數字-22.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 2,
    newGroupNumber: 23,
    path: "image/test/數字-23.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 2,
    newGroupNumber: 24,
    path: "image/test/數字-24.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 24,
    path: "image/test/數字-24.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 2,
    newGroupNumber: 25,
    path: "image/test/數字-25.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 25,
    path: "image/test/數字-25.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 26,
    path: "image/test/數字-26.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 2,
    newGroupNumber: 27,
    path: "image/test/數字-27.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 28,
    path: "image/test/數字-28.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 2,
    newGroupNumber: 29,
    path: "image/test/數字-29.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 30,
    path: "image/test/數字-30.jpg",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 2,
    newGroupNumber: 31,
    path: "image/test/數字-31.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 3,
    newGroupNumber: 32,
    path: "image/test/數字-32.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 3,
    newGroupNumber: 33,
    path: "image/test/數字-33.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 33,
    path: "image/test/數字-33.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 3,
    newGroupNumber: 34,
    path: "image/test/數字-34.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 34,
    path: "image/test/數字-34.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 3,
    newGroupNumber: 35,
    path: "image/test/數字-35.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 36,
    path: "image/test/數字-36.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 3,
    newGroupNumber: 37,
    path: "image/test/數字-37.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 38,
    path: "image/test/數字-38.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 3,
    newGroupNumber: 39,
    path: "image/test/數字-39.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 39,
    path: "image/test/數字-39.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 3,
    newGroupNumber: 40,
    path: "image/test/數字-40.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 40,
    path: "image/test/數字-40.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 3,
    newGroupNumber: 41,
    path: "image/test/數字-41.jpg",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 41,
    path: "image/test/數字-41.jpg",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 42,
    path: "image/test/數字-42.jpg",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 4,
    newGroupNumber: 43,
    path: "image/test/數字-43.jpg",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 43,
    path: "image/test/數字-43.jpg",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 4,
    newGroupNumber: 44,
    path: "image/test/數字-44.jpg",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 45,
    path: "image/test/數字-45.jpg",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 4,
    newGroupNumber: 46,
    path: "image/test/數字-46.jpg",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 47,
    path: "image/test/數字-47.jpg",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 4,
    newGroupNumber: 48,
    path: "image/test/數字-48.jpg",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 48,
    path: "image/test/數字-48.jpg",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 4,
    newGroupNumber: 49,
    path: "image/test/數字-49.jpg",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 49,
    path: "image/test/數字-49.jpg",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 4,
    newGroupNumber: 50,
    path: "image/test/數字-50.jpg",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 50,
    path: "./assets/50.glb",
    modelpath: "image/test/數字-50.jpg",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 51,
    path: "image/test/數字-51.jpg",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 5,
    newGroupNumber: 52,
    path: "image/test/數字-52.jpg",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 53,
    path: "image/test/數字-53.jpg",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 5,
    newGroupNumber: 54,
    path: "image/test/數字-54.jpg",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 55,
    path: "image/test/數字-55.jpg",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 5,
    newGroupNumber: 56,
    path: "image/test/數字-56.jpg",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 56,
    path: "image/test/數字-56.jpg",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 5,
    newGroupNumber: 57,
    path: "image/test/數字-57.jpg",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 57,
    path: "image/test/數字-57.jpg",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 5,
    newGroupNumber: 58,
    path: "image/test/數字-58.jpg",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 58,
    path: "image/test/數字-58.jpg",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 59,
    path: "image/test/數字-59.jpg",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 6,
    newGroupNumber: 60,
    path: "image/test/數字-60.jpg",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 60,
    path: "image/test/數字-60.jpg",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 61,
    path: "image/test/數字-61.jpg",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 6,
    newGroupNumber: 62,
    path: "image/test/數字-62.jpg",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 63,
    path: "image/test/數字-63.jpg",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 6,
    newGroupNumber: 64,
    path: "image/test/數字-64.jpg",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 65,
    path: "image/test/數字-65.jpg",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 6,
    newGroupNumber: 66,
    path: "image/test/數字-66.jpg",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 67,
    path: "image/test/數字-67.jpg",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 68,
    path: "image/test/數字-68.jpg",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 7,
    newGroupNumber: 69,
    path: "image/test/數字-69.jpg",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 70,
    path: "image/test/數字-70.jpg",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 7,
    newGroupNumber: 71,
    path: "image/test/數字-71.jpg",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 72,
    path: "image/test/數字-72.jpg",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 7,
    newGroupNumber: 73,
    path: "image/test/數字-73.jpg",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 74,
    path: "image/test/數字-74.jpg",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 8,
    newGroupNumber: 75,
    path: "image/test/數字-75.jpg",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 75,
    path: "image/test/數字-75.jpg",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 8,
    newGroupNumber: 76,
    path: "image/test/數字-76.jpg",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 76,
    path: "image/test/數字-76.jpg",
  },
  {
    bestNegativeGroupNumber: 9,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 77,
    path: "image/test/數字-77.jpg",
  },
  {
    bestNegativeGroupNumber: 9,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 9,
    newGroupNumber: 78,
    path: "image/test/數字-78.jpg",
  },
  {
    bestNegativeGroupNumber: 9,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 78,
    path: "image/test/數字-78.jpg",
  },
  {
    bestNegativeGroupNumber: 10,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 79,
    path: "image/test/數字-79.jpg",
    modelpath: "./assets/79.glb",
  },
];
