var data = [
  { acidity: 6.0, sweetness: 6.7, taste: 6.0 },
  { acidity: 6.3, sweetness: 5.3, taste: 4.7 },
  { acidity: 4.0, sweetness: 4.0, taste: 3.7 },
  { acidity: 4.3, sweetness: 4.7, taste: 4.7 },
  { acidity: 5.0, sweetness: 4.3, taste: 3.7 },
  { acidity: 4.7, sweetness: 6.0, taste: 6.3 },
  { acidity: 5.7, sweetness: 3.7, taste: 3.0 },
  { acidity: 4.0, sweetness: 4.3, taste: 3.7 },
  { acidity: 4.7, sweetness: 4.7, taste: 4.0 },
  { acidity: 4.3, sweetness: 5.3, taste: 5.7 },
  { acidity: 5.3, sweetness: 6.0, taste: 5.7 },
  { acidity: 6.0, sweetness: 5.7, taste: 5.0 },
  { acidity: 4.3, sweetness: 5.0, taste: 5.0 },
  { acidity: 4.7, sweetness: 6.3, taste: 5.3 },
  { acidity: 3.0, sweetness: 5.7, taste: 4.7 },
  { acidity: 5.0, sweetness: 5.3, taste: 5.0 },
  { acidity: 4.3, sweetness: 5.7, taste: 4.0 },
  { acidity: 4.3, sweetness: 5.0, taste: 5.3 },
  { acidity: 5.0, sweetness: 7.0, taste: 6.7 },
  { acidity: 5.0, sweetness: 5.0, taste: 5.0 },
  { acidity: 5.0, sweetness: 5.7, taste: 5.0 },
  { acidity: 4.0, sweetness: 5.0, taste: 4.7 },
  { acidity: 4.0, sweetness: 4.3, taste: 4.0 },
  { acidity: 3.7, sweetness: 5.3, taste: 4.7 },
  { acidity: 4.0, sweetness: 5.7, taste: 4.0 },
  { acidity: 2.7, sweetness: 5.3, taste: 4.3 },
  { acidity: 3.7, sweetness: 4.3, taste: 3.7 },
  { acidity: 3.0, sweetness: 4.0, taste: 4.3 },
  { acidity: 3.7, sweetness: 4.3, taste: 4.7 },
  { acidity: 3.7, sweetness: 4.3, taste: 4.3 },
];

const data2 = [
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 1,
    closestGroupNumber: 1,
    newGroupNumber: 1,
    path: "image/dripperinfro/濾杯結構說明 (1).jpg",
    modelpath: "./assets/01.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 2,
    closestGroupNumber: 1,
    newGroupNumber: 2,
    path: "image/dripperinfro/濾杯結構說明 (2).jpg",
    modelpath: "./assets/02.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 2,
    closestGroupNumber: 2,
    newGroupNumber: 2,
    path: "image/dripperinfro/濾杯結構說明 (2).jpg",
    modelpath: "./assets/02.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 3,
    newGroupNumber: 3,
    path: "image/dripperinfro/濾杯結構說明 (3).jpg",
    modelpath: "./assets/03.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 1,
    newGroupNumber: 4,
    path: "image/dripperinfro/濾杯結構說明 (4).jpg",
    modelpath: "./assets/04.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 5,
    path: "image/dripperinfro/濾杯結構說明 (5).jpg",
    modelpath: "./assets/05.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 1,
    newGroupNumber: 6,
    path: "image/dripperinfro/濾杯結構說明 (6).jpg",
    modelpath: "./assets/06.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 7,
    path: "image/dripperinfro/濾杯結構說明 (7).jpg",
    modelpath: "./assets/07.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 1,
    newGroupNumber: 8,
    path: "image/dripperinfro/濾杯結構說明 (8).jpg",
    modelpath: "./assets/08.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 1,
    newGroupNumber: 9,
    path: "image/dripperinfro/濾杯結構說明 (9).jpg",
    modelpath: "./assets/09.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 9,
    path: "image/dripperinfro/濾杯結構說明 (9).jpg",
    modelpath: "./assets/09.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 1,
    newGroupNumber: 10,
    path: "image/dripperinfro/濾杯結構說明 (10).jpg",
    modelpath: "./assets/10.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 10,
    path: "image/dripperinfro/濾杯結構說明 (10).jpg",
    modelpath: "./assets/10.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 11,
    path: "image/dripperinfro/濾杯結構說明 (11).jpg",
    modelpath: "./assets/11.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 1,
    newGroupNumber: 12,
    path: "image/dripperinfro/濾杯結構說明 (12).jpg",
    modelpath: "./assets/12.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 13,
    path: "image/dripperinfro/濾杯結構說明 (13).jpg",
    modelpath: "./assets/13.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 1,
    newGroupNumber: 14,
    path: "image/dripperinfro/濾杯結構說明 (14).jpg",
    modelpath: "./assets/14.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 15,
    path: "image/dripperinfro/濾杯結構說明 (15).jpg",
    modelpath: "./assets/15.glb",
  },
  {
    bestNegativeGroupNumber: 1,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 1,
    newGroupNumber: 16,
    path: "image/dripperinfro/濾杯結構說明 (16).jpg",
    modelpath: "./assets/16.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 2,
    closestGroupNumber: 2,
    newGroupNumber: 17,
    path: "image/dripperinfro/濾杯結構說明 (17).jpg",
    modelpath: "./assets/17.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 3,
    newGroupNumber: 18,
    path: "image/dripperinfro/濾杯結構說明 (18).jpg",
    modelpath: "./assets/18.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 2,
    newGroupNumber: 19,
    path: "image/dripperinfro/濾杯結構說明 (19).jpg",
    modelpath: "./assets/19.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 20,
    path: "image/dripperinfro/濾杯結構說明 (20).jpg",
    modelpath: "./assets/20.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 2,
    newGroupNumber: 21,
    path: "image/dripperinfro/濾杯結構說明 (21).jpg",
    modelpath: "./assets/21.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 22,
    path: "image/dripperinfro/濾杯結構說明 (22).jpg",
    modelpath: "./assets/22.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 2,
    newGroupNumber: 23,
    path: "image/dripperinfro/濾杯結構說明 (23).jpg",
    modelpath: "./assets/23.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 2,
    newGroupNumber: 24,
    path: "image/dripperinfro/濾杯結構說明 (24).jpg",
    modelpath: "./assets/24.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 24,
    path: "image/dripperinfro/濾杯結構說明 (24).jpg",
    modelpath: "./assets/24.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 2,
    newGroupNumber: 25,
    path: "image/dripperinfro/濾杯結構說明 (25).jpg",
    modelpath: "./assets/25.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 25,
    path: "image/dripperinfro/濾杯結構說明 (25).jpg",
    modelpath: "./assets/25.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 26,
    path: "image/dripperinfro/濾杯結構說明 (26).jpg",
    modelpath: "./assets/26.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 2,
    newGroupNumber: 27,
    path: "image/dripperinfro/濾杯結構說明 (27).jpg",
    modelpath: "./assets/27.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 28,
    path: "image/dripperinfro/濾杯結構說明 (28).jpg",
    modelpath: "./assets/28.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 2,
    newGroupNumber: 29,
    path: "image/dripperinfro/濾杯結構說明 (29).jpg",
    modelpath: "./assets/29.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 30,
    path: "image/dripperinfro/濾杯結構說明 (30).jpg",
    modelpath: "./assets/30.glb",
  },
  {
    bestNegativeGroupNumber: 2,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 2,
    newGroupNumber: 31,
    path: "image/dripperinfro/濾杯結構說明 (31).jpg",
    modelpath: "./assets/31.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 3,
    closestGroupNumber: 3,
    newGroupNumber: 32,
    path: "image/dripperinfro/濾杯結構說明 (32).jpg",
    modelpath: "./assets/32.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 3,
    newGroupNumber: 33,
    path: "image/dripperinfro/濾杯結構說明 (33).jpg",
    modelpath: "./assets/33.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 33,
    path: "image/dripperinfro/濾杯結構說明 (33).jpg",
    modelpath: "./assets/33.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 3,
    newGroupNumber: 34,
    path: "image/dripperinfro/濾杯結構說明 (34).jpg",
    modelpath: "./assets/34.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 34,
    path: "image/dripperinfro/濾杯結構說明 (34).jpg",
    modelpath: "./assets/34.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 3,
    newGroupNumber: 35,
    path: "image/dripperinfro/濾杯結構說明 (35).jpg",
    modelpath: "./assets/35.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 36,
    path: "image/dripperinfro/濾杯結構說明 (36).jpg",
    modelpath: "./assets/36.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 3,
    newGroupNumber: 37,
    path: "image/dripperinfro/濾杯結構說明 (37).jpg",
    modelpath: "./assets/37.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 38,
    path: "image/dripperinfro/濾杯結構說明 (38).jpg",
    modelpath: "./assets/38.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 3,
    newGroupNumber: 39,
    path: "image/dripperinfro/濾杯結構說明 (39).jpg",
    modelpath: "./assets/39.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 39,
    path: "image/dripperinfro/濾杯結構說明 (39).jpg",
    modelpath: "./assets/39.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 3,
    newGroupNumber: 40,
    path: "image/dripperinfro/濾杯結構說明 (40).jpg",
    modelpath: "./assets/40.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 40,
    path: "image/dripperinfro/濾杯結構說明 (40).jpg",
    modelpath: "./assets/40.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 3,
    newGroupNumber: 41,
    path: "image/dripperinfro/濾杯結構說明 (41).jpg",
    modelpath: "./assets/41.glb",
  },
  {
    bestNegativeGroupNumber: 3,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 41,
    path: "image/dripperinfro/濾杯結構說明 (41).jpg",
    modelpath: "./assets/41.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 4,
    closestGroupNumber: 4,
    newGroupNumber: 42,
    path: "image/dripperinfro/濾杯結構說明 (42).jpg",
    modelpath: "./assets/42.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 4,
    newGroupNumber: 43,
    path: "image/dripperinfro/濾杯結構說明 (43).jpg",
    modelpath: "./assets/43.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 43,
    path: "image/dripperinfro/濾杯結構說明 (43).jpg",
    modelpath: "./assets/43.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 4,
    newGroupNumber: 44,
    path: "image/dripperinfro/濾杯結構說明 (44).jpg",
    modelpath: "./assets/44.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 45,
    path: "image/dripperinfro/濾杯結構說明 (45).jpg",
    modelpath: "./assets/45.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 4,
    newGroupNumber: 46,
    path: "image/dripperinfro/濾杯結構說明 (46).jpg",
    modelpath: "./assets/46.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 47,
    path: "image/dripperinfro/濾杯結構說明 (47).jpg",
    modelpath: "./assets/47.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 4,
    newGroupNumber: 48,
    path: "image/dripperinfro/濾杯結構說明 (48).jpg",
    modelpath: "./assets/48.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 48,
    path: "image/dripperinfro/濾杯結構說明 (48).jpg",
    modelpath: "./assets/48.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 4,
    newGroupNumber: 49,
    path: "image/dripperinfro/濾杯結構說明 (49).jpg",
    modelpath: "./assets/49.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 49,
    path: "image/dripperinfro/濾杯結構說明 (49).jpg",
    modelpath: "./assets/49.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 4,
    newGroupNumber: 50,
    path: "image/dripperinfro/濾杯結構說明 (50).jpg",
    modelpath: "./assets/50.glb",
  },
  {
    bestNegativeGroupNumber: 4,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 50,
    path: "image/dripperinfro/濾杯結構說明 (50).jpg",
    modelpath: "./assets/50.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 5,
    closestGroupNumber: 5,
    newGroupNumber: 51,
    path: "image/dripperinfro/濾杯結構說明 (51).jpg",
    modelpath: "./assets/51.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 5,
    newGroupNumber: 52,
    path: "image/dripperinfro/濾杯結構說明 (52).jpg",
    modelpath: "./assets/52.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 53,
    path: "image/dripperinfro/濾杯結構說明 (53).jpg",
    modelpath: "./assets/53.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 5,
    newGroupNumber: 54,
    path: "image/dripperinfro/濾杯結構說明 (54).jpg",
    modelpath: "./assets/54.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 55,
    path: "image/dripperinfro/濾杯結構說明 (55).jpg",
    modelpath: "./assets/55.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 5,
    newGroupNumber: 56,
    path: "image/dripperinfro/濾杯結構說明 (56).jpg",
    modelpath: "./assets/56.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 56,
    path: "image/dripperinfro/濾杯結構說明 (56).jpg",
    modelpath: "./assets/56.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 5,
    newGroupNumber: 57,
    path: "image/dripperinfro/濾杯結構說明 (57).jpg",
    modelpath: "./assets/57.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 57,
    path: "image/dripperinfro/濾杯結構說明 (57).jpg",
    modelpath: "./assets/57.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 5,
    newGroupNumber: 58,
    path: "image/dripperinfro/濾杯結構說明 (58).jpg",
    modelpath: "./assets/58.glb",
  },
  {
    bestNegativeGroupNumber: 5,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 58,
    path: "image/dripperinfro/濾杯結構說明 (58).jpg",
    modelpath: "./assets/58.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 6,
    closestGroupNumber: 6,
    newGroupNumber: 59,
    path: "image/dripperinfro/濾杯結構說明 (59).jpg",
    modelpath: "./assets/59.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 6,
    newGroupNumber: 60,
    path: "image/dripperinfro/濾杯結構說明 (60).jpg",
    modelpath: "./assets/60.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 60,
    path: "image/dripperinfro/濾杯結構說明 (60).jpg",
    modelpath: "./assets/60.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 61,
    path: "image/dripperinfro/濾杯結構說明 (61).jpg",
    modelpath: "./assets/61.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 6,
    newGroupNumber: 62,
    path: "image/dripperinfro/濾杯結構說明 (62).jpg",
    modelpath: "./assets/62.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 63,
    path: "image/dripperinfro/濾杯結構說明 (63).jpg",
    modelpath: "./assets/63.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 6,
    newGroupNumber: 64,
    path: "image/dripperinfro/濾杯結構說明 (64).jpg",
    modelpath: "./assets/64.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 65,
    path: "image/dripperinfro/濾杯結構說明 (65).jpg",
    modelpath: "./assets/65.glb",
  },
  {
    bestNegativeGroupNumber: 6,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 6,
    newGroupNumber: 66,
    path: "image/dripperinfro/濾杯結構說明 (66).jpg",
    modelpath: "./assets/66.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 7,
    closestGroupNumber: 7,
    newGroupNumber: 67,
    path: "image/dripperinfro/濾杯結構說明 (67).jpg",
    modelpath: "./assets/67.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 68,
    path: "image/dripperinfro/濾杯結構說明 (68).jpg",
    modelpath: "./assets/68.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 7,
    newGroupNumber: 69,
    path: "image/dripperinfro/濾杯結構說明 (69).jpg",
    modelpath: "./assets/69.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 70,
    path: "image/dripperinfro/濾杯結構說明 (70).jpg",
    modelpath: "./assets/70.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 7,
    newGroupNumber: 71,
    path: "image/dripperinfro/濾杯結構說明 (71).jpg",
    modelpath: "./assets/71.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 72,
    path: "image/dripperinfro/濾杯結構說明 (72).jpg",
    modelpath: "./assets/72.glb",
  },
  {
    bestNegativeGroupNumber: 7,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 7,
    newGroupNumber: 73,
    path: "image/dripperinfro/濾杯結構說明 (73).jpg",
    modelpath: "./assets/73.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 8,
    closestGroupNumber: 8,
    newGroupNumber: 74,
    path: "image/dripperinfro/濾杯結構說明 (74).jpg",
    modelpath: "./assets/74.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 8,
    newGroupNumber: 75,
    path: "image/dripperinfro/濾杯結構說明 (75).jpg",
    modelpath: "./assets/75.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 75,
    path: "image/dripperinfro/濾杯結構說明 (75).jpg",
    modelpath: "./assets/75.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 8,
    newGroupNumber: 76,
    path: "image/dripperinfro/濾杯結構說明 (76).jpg",
    modelpath: "./assets/76.glb",
  },
  {
    bestNegativeGroupNumber: 8,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 76,
    path: "image/dripperinfro/濾杯結構說明 (76).jpg",
    modelpath: "./assets/76.glb",
  },
  {
    bestNegativeGroupNumber: 9,
    bestNonNegativeGroupNumber: 9,
    closestGroupNumber: 9,
    newGroupNumber: 77,
    path: "image/dripperinfro/濾杯結構說明 (77).jpg",
    modelpath: "./assets/77.glb",
  },
  {
    bestNegativeGroupNumber: 9,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 9,
    newGroupNumber: 78,
    path: "image/dripperinfro/濾杯結構說明 (78).jpg",
    modelpath: "./assets/78.glb",
  },
  {
    bestNegativeGroupNumber: 9,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 78,
    path: "image/dripperinfro/濾杯結構說明 (78).jpg",
    modelpath: "./assets/78.glb",
  },
  {
    bestNegativeGroupNumber: 10,
    bestNonNegativeGroupNumber: 10,
    closestGroupNumber: 10,
    newGroupNumber: 79,
    path: "image/dripperinfro/濾杯結構說明 (79).jpg",
    modelpath: "./assets/79.glb",
  },
];
